<?php
require __DIR__ . '/vendor/autoload.php';

use Dompdf\Dompdf;
use Dompdf\Options;

if ($_SERVER['REQUEST_METHOD'] === 'POST') {

    $html_content = '<style>
        @page {
            margin-left: 40px;
            margin-right: 40px;
            margin-bottom: 60px; /* Enough room for footer */
        }
        body {
            font-family: sans-serif;
            font-size: 10pt;
            margin: 0; padding: 0;
        }

        table {
            border-collapse: collapse;
            width: 100%;
            margin-bottom: 20px;
        }
        th, td {
            border: 1px solid #000;
            padding: 5px;
            text-align: center;
        }
        th {
            background-color: #0E172D;
            color: #fff;
        }

        /* The crucial sub-table widths */
        .calc-subtable {
            width: 100%;
            table-layout: fixed;
            border-collapse: collapse;
        }
        .calc-subtable col:first-child {
            width: 22%;
        }
        .calc-subtable col:nth-child(n+2) {
            width: 5.2%;
        }
    </style>';

    // Optional logo
    $html_content .= '
    <div style="text-align:right;">
        <img src="https://projectdesign.io/wp-content/uploads/2024/07/L-CN_Logo-Circle-Navy.svg" alt="Logo" style="height:50px;">
    </div>';

    // Project info
    $html_content .= '<div style="margin-bottom:20px;">
        <strong>Project:</strong> ' . htmlspecialchars($_POST['pdf_project']) . '<br>
        <strong>Date:</strong> ' . htmlspecialchars($_POST['pdf_date']) . '<br>
        <strong>Revision:</strong> ' . htmlspecialchars($_POST['pdf_revision']) . '<br>
        <strong>Generator Description:</strong> ' . htmlspecialchars($_POST['pdf_gen_desc']) . '<br>
    </div>';

    // Insert the HTML from calculate.php
    if (!empty($_POST['results'])) {
        $html_content .= $_POST['results'];
    }

    // Disclaimer
    $html_content .= '
    <div style="margin-top:40px; text-align:left;">
        <h3>DISCLAIMER</h3>
        <p>This generator sizing tool is provided for informational purposes only. The calculations and recommendations produced by this tool are based on the data entered by the user and do not replace professional engineering judgment.</p>
        <p><strong>No Warranty or Guarantee:</strong> The results generated by this tool are estimates and do not guarantee compliance with local, state, or national electrical or safety codes. It is the responsibility of the user to verify all calculations and ensure compliance with applicable regulations and industry standards.</p>
        <p><strong>Limitation of Liability:</strong> The provider of this tool assumes no liability for damages, losses, or risks arising from its use. Users should consult a licensed electrical engineer or relevant authority before making any purchasing or installation decisions.</p>
        <p><strong>Code Compliance:</strong> Local codes, manufacturer specifications, and site conditions can significantly impact generator sizing. This tool does not account for all potential variables. Always confirm sizing requirements with a qualified professional before proceeding with installation.</p>
    </div>';

    // Footer
    $html_content .= '
    <div class="footer-right">
        powered by PROJECT DESIGN (IO)
    </div>';

    // Dompdf
    $options = new Options();
    $options->set('isRemoteEnabled', true);
    $dompdf = new Dompdf($options);

    $dompdf->loadHtml($html_content);
    $dompdf->setPaper('A2', 'portrait');
    $dompdf->render();

    // Write PDF to file
    $pdf_output = $dompdf->output();
    file_put_contents(__DIR__ . "/generator-load-report.pdf", $pdf_output);

    // Return PDF URL
    echo plugins_url("generator-load-report.pdf", __FILE__);
    wp_die();
}
